development:
  secret_key_base: bf0b596812f1a826e1f49bc513318d3bd520185e0b37a8178acad039ce0e3268746211e14f26b5f5b1fac4581e527900557097ff1fe3cbf41dcf62188f0a0bf9
  recaptcha_site_key: <%= ENV["RECAPTCHA_SITE_KEY"] %>
  recaptcha_secret_key: <%= ENV["RECAPTCHA_SECRET_KEY"] %>

test:
  secret_key_base: bf0b596812f1a826e1f49bc513318d3bd520185e0b37a8178acad039ce0e3268746211e14f26b5f5b1fac4581e527900557097ff1fe3cbf41dcf62188f0a0bf9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  recaptcha_site_key: <%= ENV["RECAPTCHA_SITE_KEY"] %>
  recaptcha_secret_key: <%= ENV["RECAPTCHA_SECRET_KEY"] %>
